### PR TITLE
Create the Algorithm for JAVA 

### PR DESCRIPTION
**Pull request by ragupathi09**
binary search in pyton

### CODE REVIEW

**Comment by odusgowtham** [comment]
bro , your work is good , but this repository is only for java dsa and java related programs, make a new PR with any java programs

**Comment by ragupathi09** [comment]
Sure Gowtham

**Comment by odusgowtham** [comment]
hi bro , why didn't added anything

**Comment by ragupathi09** [comment]
> hi bro , why didn't added anything

Thanks for asking please verify

**Comment by odusgowtham** [comment]
NICE WORK BRO

**Pull request merged**
